ascii_art:
  header: |
    ╔══════════════════════════════════════════════════════════╗
    ║ The Ultimate Overengineered Question Generator 3.0       ║
    ║ "Because simple code is for the weak"                   ║
    ╚══════════════════════════════════════════════════════════╝
  footer: |
    ╔══════════════════════════════════════════════════════════╗
    ║ Remember: With great power comes great complexity        ║
    ╚══════════════════════════════════════════════════════════╝

feature_flags:
  enable_excessive_punctuation: false
  enable_philosophical_prefix: true
  enable_reverse_text: false
